=== zhu-2002/imooc_learning/out/production/imooc_learning/xml/hr.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!--        当前文档引用的别名,当作全局默认的文档约束生效-->
<schema xmlns="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://ww.imooc.com/xml-schema" elementFormDefault="qualified">
    <element name="hr">
<!--        当前标签下是父子混合标签,用complexType-->
        <complexType>
            <sequence>
                <element name="employee" minOccurs="1" maxOccurs="99999">
                    <complexType>
                        <sequence>
                            <element name="name" type="string"></element>
                            <element name="age" >
                                <simpleType>
<!--                                    声明类型-->
                                    <restriction base="integer">
<!--                                        Inclusive是闭区间，包含该点-->
                                        <minInclusive value="21"></minInclusive>
                                        <maxInclusive value="35"></maxInclusive>
                                    </restriction>
                                </simpleType>
                            </element>
                            <element name="salary" type="integer"></element>
                            <element name="department">
                                <complexType>
                                    <sequence>
                                        <element name="dname" type="string"></element>
                                        <element name="address" type="string"></element>
                                    </sequence>
                                </complexType>
                            </element>
                        </sequence>
                        <attribute name="eno" type="string" use="required"></attribute>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
</schema>

=== zhu-2002/imooc_learning/src/xml/hr_schema.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!--公司员工数据-->
<!--第一项引用默认的命名空间,后两项几乎是写死的-->
<hr xmlns="http://ww.imooc.com/xml-schema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://ww.imooc.com/xml-schema hr.xsd">
    <employee eno="2025020125">
        <name>Zenos</name>
        <age>22</age>
        <salary>4000</salary>
        <department>
            <dname>研发部</dname>
            <address>xx大厦-204</address>
        </department>
    </employee>
    <employee eno="2025020105">
        <name>Maria</name>
        <age>21</age>
        <salary>2000</salary>
        <department>
            <dname>会计部</dname>
            <address>xx大厦-105</address>
        </department>
    </employee>
</hr>
